DROP SEQUENCE MEMBER_NUMBER_SEQ;
DROP SEQUENCE PREFER_GENRE_NUMBER_SEQ;
DROP SEQUENCE POST_COMMENT_NUMBER_SEQ;
DROP SEQUENCE BOARD_NUMBER_SEQ;
DROP SEQUENCE HEART_NUMBER_SEQ;
DROP SEQUENCE WATCH_NUMBER_SEQ;
DROP SEQUENCE ORDER_HISTORY_NUMBER_SEQ;
DROP SEQUENCE BASKET_NUMBER_SEQ;
DROP SEQUENCE LINE_REVIEW_NUMBER_SEQ;
DROP SEQUENCE RATING_NUMBER_SEQ;
DROP SEQUENCE ORDER_PRODUCT_NUMBER_SEQ;
DROP SEQUENCE MOVIE_NUMBER_SEQ;
DROP SEQUENCE MOVIE_POSTER_NUMBER_SEQ;
DROP SEQUENCE MOVIE_STILLCUT_NUMBER_SEQ;
DROP SEQUENCE ACTOR_NUMBER_SEQ;
DROP SEQUENCE DIRECTOR_NUMBER_SEQ;
DROP SEQUENCE CAST_MEMBER_NUMBER_SEQ;


------------------------------------------------------------------------
CREATE SEQUENCE MEMBER_NUMBER_SEQ
INCREMENT BY 1
START WITH 100;


CREATE SEQUENCE PREFER_GENRE_NUMBER_SEQ
INCREMENT BY 1
START WITH 1;


CREATE SEQUENCE POST_COMMENT_NUMBER_SEQ
INCREMENT BY 1
START WITH 1;


CREATE SEQUENCE BOARD_NUMBER_SEQ
INCREMENT BY 1
START WITH 1;


CREATE SEQUENCE HEART_NUMBER_SEQ
INCREMENT BY 1
START WITH 1;


CREATE SEQUENCE WATCH_NUMBER_SEQ
INCREMENT BY 1
START WITH 1;


CREATE SEQUENCE BASKET_NUMBER_SEQ
INCREMENT BY 1
START WITH 1;


CREATE SEQUENCE ORDER_HISTORY_NUMBER_SEQ
INCREMENT BY 1
START WITH 1;


CREATE SEQUENCE LINE_REVIEW_NUMBER_SEQ
INCREMENT BY 1
START WITH 1;


CREATE SEQUENCE RATING_NUMBER_SEQ
INCREMENT BY 1
START WITH 1;


CREATE SEQUENCE ORDER_PRODUCT_NUMBER_SEQ
INCREMENT BY 1
START WITH 1;

CREATE SEQUENCE MOVIE_NUMBER_SEQ
INCREMENT BY 1
START WITH 1;

CREATE SEQUENCE MOVIE_POSTER_NUMBER_SEQ
INCREMENT BY 1
START WITH 1;

CREATE SEQUENCE MOVIE_STILLCUT_NUMBER_SEQ
INCREMENT BY 1
START WITH 1;

CREATE SEQUENCE ACTOR_NUMBER_SEQ
INCREMENT BY 1
START WITH 1;

CREATE SEQUENCE DIRECTOR_NUMBER_SEQ
INCREMENT BY 1
START WITH 1;

CREATE SEQUENCE CAST_MEMBER_NUMBER_SEQ
INCREMENT BY 1
START WITH 1;
