-- 감독 넣기
SELECT * FROM DIRECTOR;
SELECT * FROM temp_director;

INSERT INTO DIRECTOR (DIRECTOR_NUMBER, DIRECTOR_NAME)
SELECT DIRECTOR_NUMBER_SEQ.nextval, DIRECTOR_NAME
FROM temp_director
WHERE NOT DIRECTOR_NAME IS NULL;


-- 영화 넣기
SELECT * FROM MOVIE;
DESC TEMP_MOVIE;

INSERT INTO MOVIE(MOVIE_NUMBER, MOVIE_CD, MOVIE_TITLE, MOVIE_SUMMARY, MOVIE_RELEASE_DATE, MOVIE_RUNTIME, MOVIE_PRICE, MOVIE_PREVIEW, MOVIE_RATING, MOVIE_MAIN_POSTER, GENRE_NUMBER)
SELECT MOVIE_NUMBER_SEQ.NEXTVAL, TM.MOVIECD, TM.MOVIE_TITLE, TM.MOVIE_SUMMARY, TM.MOVIE_RELEASE_DATE, TM.MOVIE_RUN_TIME, 10000, TM.MOVIE_PREVIEW, TM.MOVIE_RATING, TM.MOVIE_MAIN_POSTER, TM.GENRE_NAME
FROM TEMP_MOVIE TM;

UPDATE MOVIE M
SET DIRECTOR_NUMBER = ( SELECT DIRECTOR_NUMBER
                        FROM DIRECTOR D JOIN TEMP_DIRECTOR TD
                        ON d.director_name = td.director_name
                        WHERE M.MOVIE_CD = TD.MOVIECD)
;
-- 포스터 넣기
SELECT * FROM MOVIE_POSTER;
SELECT * FROM temp_movie_poster;

INSERT INTO MOVIE_POSTER (MOVIE_POSTER_NUMBER, MOVIE_POSTER_ADDRESS, MOVIE_NUMBER)
SELECT MOVIE_POSTER_NUMBER_SEQ.NEXTVAL, TMP.MOVIESIDEPOSTER, M.MOVIE_NUMBER
FROM TEMP_MOVIE_POSTER TMP JOIN MOVIE M
ON TMP.MOVIECD = M.MOVIE_CD;


-- 스틸컷 넣기
SELECT * FROM MOVIE_STILLCUT;
SELECT * FROM TEMP_MOVIE_STILLCUT;

INSERT INTO MOVIE_STILLCUT (MOVIE_STILLCUT_NUMBER, MOVIE_STILLCUT_ADDRESS, MOVIE_NUMBER)
SELECT MOVIE_STILLCUT_NUMBER_SEQ.NEXTVAL, TMS.MOVIE_STILLCUT_ADDRESS, M.MOVIE_NUMBER
FROM TEMP_MOVIE_STILLCUT TMS JOIN MOVIE M
ON TMS.MOVIECD = M.MOVIE_CD;


-- 배우 넣기
SELECT * FROM ACTOR;
SELECT * FROM TEMP_CAST;

INSERT INTO ACTOR (ACTOR_NUMBER, ACTOR_NAME)
SELECT ACTOR_NUMBER_SEQ.NEXTVAL, MOVIECAST
FROM TEMP_CAST;


--영화 출연자 넣기
SELECT * FROM CAST_MEMBER;
SELECT * FROM TEMP_CAST;

INSERT INTO CAST_MEMBER (CAST_MEMBER_NUMBER, MOVIE_NUMBER, ACTOR_NUMBER)
SELECT CAST_MEMBER_NUMBER_SEQ.NEXTVAL, M.MOVIE_NUMBER, A.ACTOR_NUMBER
FROM MOVIE M JOIN TEMP_CAST TC
ON M.MOVIE_CD = TC.MOVIECD
JOIN ACTOR A
ON TC.MOVIECAST = A.ACTOR_NAME;

